### ISSUE TITLE
Schema validation: Validates to more than one variant

### ISSUE THREAD

**Issue by ohcnkk** [cedricziel/idea-concourse#36]
Error message.

`Schema validation: Validates to more than one variant`

How to reproduce.

```yaml
jobs:
  - name: build-and-push
    plan:
      - in_parallel:
          - get: python
          - get: awscli
          - get: pipelines
          - get: alpine-image
```
